### ISSUE TITLE
Fatal error on elb_client.describe_tags

### ISSUE THREAD

**Issue by marek-obuchowicz** [zalando/zmon-aws-agent#13]
The commit https://github.com/zalando/zmon-aws-agent/commit/ba70e59f33f20dd0e42670e33b31a64841317ae6 introduced fatal error, since this commit ELB discovery is not working and agent is broken for us completely:
```
Traceback (most recent call last):
  File "/zmon-agent.py", line 522, in <module>
    main()
  File "/zmon-agent.py", line 405, in main
    elbs = get_running_elbs(region, infrastructure_account)
  File "/zmon-agent.py", line 178, in get_running_elbs
    tag_desc = elb_client.describe_tags(LoadBalancerNames=elb_names)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 382, in _make_api_call
    api_params, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 423, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/validate.py", line 273, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter LoadBalancerNames, value: 62, valid range: 1-20
```

**Comment by Jan-M** [comment]
I did not see that we introduced something new, which indeed we did with the tags.

@a1exsh can you look into this? seems to need paging.

**Comment by a1exsh** [comment]
Oops, will work on a fix.

**Comment by marek-obuchowicz** [comment]
Thanks, it looks fine
