### ISSUE TITLE
zmon-agent KeyError

### ISSUE THREAD

**Issue by mircof** [zalando/zmon-aws-agent#21]
zmon-agent version: 0.46 running on AWS
Error inside the application.log

Traceback (most recent call last):
File "/zmon-agent.py", line 543, in <module>
 main()
File "/zmon-agent.py", line 423, in main
 apps = get_running_apps(region)
 File "/zmon-agent.py", line 162, in get_running_apps
  ins['resource_id'] = tags['aws:cloudformation:logical-id']
KeyError: 'aws:cloudformation:logical-id'
sleeping...

**Comment by Jan-M** [comment]
Closed in latest commit.
